### PR TITLE
feat(fileserver): new static files server

### PR DESCRIPTION
**Pull request by rustatian**
# Reason for This PR

- closes: #50 

## Description of Changes

- New separate `fileserver` plugin to serve static files.
- Supports etags, prefixes, max_age, cache duration, etc
- Independent from the HTTP plugin, thus doesn't affect the performance.

Config: 
```yaml
fileserver:
  # File server address
  #
  # Error on empty
  address: 127.0.0.1:10101
  # Etag calculation. Request body CRC32.
  #
  # Default: false
  calculate_etag: true

  # Weak etag calculation
  #
  # Default: false
  weak: false

  # Enable body streaming for files more than 4KB
  #
  # Default: false
  stream_request_body: true

  serve:
    # HTTP prefix
    #
    # Error on empty
  - prefix: "/foo"

    # Directory to serve
    #
    # Default: "."
    root: "../../../tests"

    # When set to true, the server tries minimizing CPU usage by caching compressed files
    #
    # Default: false
    compress: false

    # Expiration duration for inactive file handlers. Units: seconds.
    #
    # Default: 10, use a negative value to disable it.
    cache_duration: 10

    # The value for the Cache-Control HTTP-header. Units: seconds
    #
    # Default: 10 seconds
    max_age: 10

    # Enable range requests
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
    #
    # Default: false
    bytes_range: true

  - prefix: "/foo/bar"
    root: "../../../tests"
    compress: false
    cache_duration: 10
    max_age: 10
    bytes_range: true
```

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by victor-sudakov** [comment]
I don't quite understand the idea. Does this new static files server listen on a port different from http.address? It was great that RR could serve both static and dynamic content on the same port (it worked much like try_files in nginx), but now is that impossible?

**Comment by rustatian** [comment]
> I don't quite understand the idea. Does this new static files server listen on a port different from http.address? It was great that RR could serve both static and dynamic content on the same port (it worked much like try_files in nginx), but now is that impossible?

There are no changes to the existing static files middleware. You may use it as usual and serve static and dynamic content.

**Comment by rustatian** [comment]
`fileserver` is a standalone plugin with its own configuration independent from the HTTP plugin.

**Comment by victor-sudakov** [comment]
> fileserver is a standalone plugin with its own configuration independent from the HTTP plugin.

Are you planning to add multiple path/prefix/root support to the static files middleware?

A standalone static file server does not have much value IMHO, as you can always use nginx for that. The real zest is in being able to serve both static and dynamic files from one HTTP endpoint.

**Comment by rustatian** [comment]
> Are you planning to add multiple path/prefix/root support to the static files middleware?

Only after https://github.com/spiral/roadrunner-plugins/issues/32. We can't break behavior for the existing users w/o configuration versioning.

> A standalone static file server does not have much value IMHO, as you can always use nginx for that.

For you personally 😃 But not for all RR users.

> The real zest is in being able to serve both static and dynamic files from one HTTP endpoint.

Let's see how much interest will be in your FR and if users vote for this feature, I'll raise the priority for it. I'll reopen the original issue.

**Comment by victor-sudakov** [comment]
> > A standalone static file server does not have much value IMHO, as you can always use nginx for that.
> 
> For you personally smiley But not for all RR users.

Well, I can enumerate all the static prefixes in Ingress configuration and send them to a different service/port. It will just look less graceful :-)

**Comment by rustatian** [comment]
Yeahh 😄 As for the RR, I'll try to do my best as soon as possible to upgrade the `static` middleware as we discussed in the ticket, but I have to take into account other users with the tickets with higher priority.

**Pull request merged**
