### PR TITLE
feat(acme): letsencrypt acme provider

### PR DESCRIPTION
**Pull request by rustatian**
# Reason for This PR

closes: #21 

## Let's encrypt support

Configuration:
```json
{
  "rpc": {
    "listen": "tcp://127.0.0.1:6001"
  },
  "server": {
    "command": "php ../roadrunner/tests/psr-worker-bench.php",
    "relay": "pipes",
    "relay_timeout": "20s"
  },
  "http": {
    "address": "127.0.0.1:15389",
    "max_request_size": 256,
    "middleware": [],
    "ssl": {
      "address": ":443",
      "acme": {
        "certs_dir": "le_certs",
        "email": "your@mail.here",
        "private_key_name": "test.key",
        "certificate_name": "test.crt",
        "challenge_type": "tlsalpn-01",
        "challenge_port": "443",
        "use_production_endpoint": false,
        "domains": [
          "you_domain_here.me"
        ],
        "obtain_certificates": true
      }
    },
    "pool": {
      "num_workers": 10,
      "allocate_timeout": "60s",
      "destroy_timeout": "60s"
    }
  },
  "logs": {
    "mode": "development",
    "level": "debug"
  }
}
```

- New configuration section: `acme` in the `ssl`.
Fields legend:
- `cache_dir`: directory where to store (or where pk and cert already stored) pk and cert obtained from the LE. By default, RR creates `rr_cache_dir` in the working directory.
- `email`: your email. Mandatory field, needed for your certificate request account.
- `private_key_name` and `certificate_name`: names for your PK and crt w/o directory. They will be stored in the `cache_dir`. By default key and crt will have the following names: `private.key`, `certificate.crt` with the `0600` and `0644` permissions accordingly.
- `challenge_type`: LE challenges (https://letsencrypt.org/docs/challenge-types/). Supported values are: `http-01` and `tlsalpn-01`.
- `challenge_port`: might be any port, BUT if it differs from the standard 80 and 443 for the `http` and `tls` challenges, to pass the check, traffic should be reversed to these ports.
- `use_production_endpoint`: by default: false. Use staging LE endpoint to check if your server is ready (ports are open, etc).
- `domains`: array with the domain names to register.
- `obtain_certificates`: false by default. Used as a final fuse before certificate request. LE has a rate limit, so, you should be sure, that everything is fine. [Link](https://letsencrypt.org/docs/rate-limits/).

--------

- Folders structure, initial architecture design.

Arch [alpha]:

image

Description:
We should support different types of protocols to communicate with the world. However, with existing architecture, we are forced to extend big, monolithic HTTP `plugin` to support HTTP, HTTPS, FCGI, HTTP3 (in future), WS, and other types of protocols. Updated architecture has as its goal to split different protocols (HTTP 1.1, HTTP 2, QUIC (HTTP 3) ... etc) into pluggable drivers under the plugin called `transport` (might be changed).

Transport plugin collects all protocol drivers, middleware for every driver (for example, GRPC uses interceptors) and exposes them. If there is not enough speed for the Go's std-http (for example), we may easily replace it with `fasthttp` or any other faster driver. The most interesting part here is that protocol drivers become independent and don't use abstractions from the different protocols to check if the user specifies some of them in the configuration. Code become cleaner and easier to support.

Diagram looks simple, but there are many problems to solve, such as:
- Shared worker pool to support existing configuration.
- Common interface to initialize/serve the driver. It should be simple and powerful to support many different types of protocols.
- Failures handling.
- RPC control interface (??).
- `Reset` and `Workers` calls should return proper stats.

## License Acceptance

By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.

## PR Checklist

`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

- [x] All commits in this PR are signed (`git commit -s`).
- [x] The reason for this PR is clearly provided (issue no. or explanation).
- [x] The description of changes is clear and encompassing.
- [x] Any required documentation changes (code and docs) are included in this PR.
- [x] Any user-facing changes are mentioned in `CHANGELOG.md`.
- [x] All added/changed functionality is tested.

### CODE REVIEW

**Comment by francislavoie** [comment]
Maybe consider changing the `ssl` config field to `tls`. SSL is a deprecated term. It's now called TLS.

**Comment by francislavoie** [comment]
Have you considered using `certmagic` instead of `lego`? https://github.com/caddyserver/certmagic is a more robust implementation, and is what Caddy uses under the hood.

**Comment by rustatian** [comment]
> Have you considered using `certmagic` instead of `lego`? https://github.com/caddyserver/certmagic is a more robust implementation, and is what Caddy uses under the hood.

Yeah, I saw `certmagic`, but we use a very small fraction of what `certmagic` or `lego` may provide. In the previous implementation, I used only `crypto/acme` from stdlib, and that was fine for us 😄 (but, tbh, lego might be swapped with certmagic before release, there is no final decision yet)

**Comment by rustatian** [comment]
@francislavoie I'll wait for the certmagic `v1.0.0` release (https://github.com/caddyserver/certmagic/commit/1bbe11e2914b8487f2c55ba72108844133dbd203#r56974345). Just to be sure, that there is no BC.

**Comment by rustatian** [comment]
But from the API pov, `certmagic` looks better than `lego`, hmm, dilemma. @francislavoie Thanks, I'll think about using `certmagic`.

**Comment by mholt** [comment]
Yeah, CertMagic has a much better API. I'll tag v0.15.0 in a few minutes with one BC. Note that breaking changes are very uncommon at this point and are documented in release notes, and might only affect some users when they do happen. I do want to tag a v1.0 at some point, hopefully by the end of the year. We'll see.

**Comment by rustatian** [comment]
Great, thanks for clarifying @mholt

**Pull request merged**
